import { useEffect, useState } from 'react'
import { useAuth0 } from '@auth0/auth0-react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { MapPin, Package, ChevronRight, Loader2, Navigation, CheckCircle } from 'lucide-react'
import toast from 'react-hot-toast'
import { useApi } from '../hooks/useApi.js'
import { api, setAuthToken } from '../config/api.js'
import Navbar from '../components/layout/Navbar.jsx'
import DeliveryTrackingMap from '../components/delivery/DeliveryTrackingMap.jsx'
import './DriverDashboard.css'

const DISTRICTS = ['Miraflores','San Isidro','Barranco','Surco','La Molina','San Borja','Cercado de Lima','Lince','Jesús María','Magdalena','San Miguel','Pueblo Libre','Breña','Rímac','Los Olivos','San Martín de Porres','Ate','La Victoria','Chorrillos']

export default function DriverDashboard() {
  const { getAccessTokenSilently, isAuthenticated } = useAuth0(); useApi()
  const qc = useQueryClient(), [district,setDistrict]=useState(''), [busy,setBusy]=useState(null), [position,setPosition]=useState(null)
  const auth = async () => setAuthToken(await getAccessTokenSilently({ authorizationParams:{ audience:import.meta.env.VITE_AUTH0_AUDIENCE } }))
  const { data:active=[] } = useQuery({ queryKey:['driver-active-orders'], queryFn:async()=>{await auth();return (await api.get('/api/v1/drivers/orders/active')).data.data}, enabled:isAuthenticated, refetchInterval:5000 })
  const { data:orders=[],isLoading,refetch } = useQuery({ queryKey:['driver-orders',district], queryFn:async()=>{await auth();return (await api.get('/api/v1/drivers/orders/available',{params:{district}})).data.data}, enabled:isAuthenticated&&!!district&&!active.length, refetchInterval:active.length?false:10000 })

  useEffect(()=>{ if(!isAuthenticated||!navigator.geolocation)return; const id=navigator.geolocation.watchPosition(async({coords})=>{const p={latitude:coords.latitude,longitude:coords.longitude};setPosition(p);try{setAuthToken(await getAccessTokenSilently({authorizationParams:{audience:import.meta.env.VITE_AUTH0_AUDIENCE}}));await api.patch('/api/v1/drivers/location',p)}catch(error){void error}},()=>{},{enableHighAccuracy:true,maximumAge:5000,timeout:12000});return()=>navigator.geolocation.clearWatch(id) },[isAuthenticated,getAccessTokenSilently])
  const accept=async id=>{setBusy(id);try{await auth();await api.patch(`/api/v1/orders/${id}/assign-driver`);toast.success('Pedido tomado. Ve al restaurante.');await qc.invalidateQueries({queryKey:['driver-active-orders']});refetch()}catch(e){toast.error(e.response?.data?.message||'No se pudo tomar el pedido')}finally{setBusy(null)}}
  const advance=async o=>{const status=o.status==='READY'?'ON_THE_WAY':'DELIVERED';setBusy(o.id);try{await auth();await api.patch(`/api/v1/orders/${o.id}/status`,{status});toast.success(status==='ON_THE_WAY'?'Entrega en camino':'Entrega completada');qc.invalidateQueries({queryKey:['driver-active-orders']})}catch(e){toast.error(e.response?.data?.message||'No se pudo actualizar')}finally{setBusy(null)}}
  const current=active[0]
  return <div className="ddash"><Navbar/><div className="ddash-inner"><h1 className="ddash-title">Panel de repartidor</h1>
    {current?<section className="ddash-active"><div className="ddash-active-head"><div><span className="ddash-live">● ENTREGA ACTIVA</span><h2>#{current.orderNumber?.slice(-8)}</h2></div><strong>S/ {current.total?.toFixed(2)}</strong></div><p><Package size={15}/> Recoger en <strong>{current.restaurant?.name}</strong>: {current.restaurant?.address}</p><p><MapPin size={15}/> Entregar a <strong>{current.user?.name}</strong>: {current.deliveryAddress}</p><DeliveryTrackingMap restaurant={current.restaurant} destination={{latitude:current.deliveryLatitude,longitude:current.deliveryLongitude}} driver={{...position,name:'Mi ubicación'}}/><div className="ddash-active-actions"><a className="ddash-route" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${current.status==='READY'?`${current.restaurant?.latitude},${current.restaurant?.longitude}`:`${current.deliveryLatitude},${current.deliveryLongitude}`}`}><Navigation size={16}/> Abrir ruta</a><button className="dorder-accept" disabled={busy===current.id} onClick={()=>advance(current)}>{busy===current.id?<Loader2 size={15} className="ddash-spinner"/>:<CheckCircle size={15}/>} {current.status==='READY'?'Ya recogí el pedido':'Confirmar entrega'}</button></div><small className="ddash-tracking">ID de delivery: {current.id}</small></section>:<><div className="ddash-zone"><h2 className="ddash-zone-title"><MapPin size={18}/> Buscar pedidos por zona</h2><select className="ddash-select" value={district} onChange={e=>setDistrict(e.target.value)}><option value="">Selecciona un distrito</option>{DISTRICTS.map(d=><option key={d}>{d}</option>)}</select></div>{!district&&<div className="ddash-empty"><Package size={40}/><p>Selecciona un distrito para ver pedidos</p></div>}{district&&isLoading&&<div className="ddash-loading"><Loader2 className="ddash-spinner"/></div>}<div className="ddash-orders">{orders.map(o=><div className="dorder" key={o.id}><div className="dorder-header"><div><p className="dorder-number">#{o.orderNumber?.slice(-8)}</p><p className="dorder-restaurant">{o.restaurant?.name}</p></div></div><div className="dorder-delivery"><MapPin size={13}/>{o.deliveryAddress}, {o.deliveryDistrict}</div><div className="dorder-footer"><b>S/ {o.total?.toFixed(2)}</b><button className="dorder-accept" onClick={()=>accept(o.id)} disabled={busy===o.id}>{busy===o.id?<Loader2 className="ddash-spinner" size={14}/>:<ChevronRight size={14}/>} Tomar pedido</button></div></div>)}</div>{district&&!isLoading&&!orders.length&&<div className="ddash-empty"><p>No hay pedidos disponibles ahora mismo</p></div>}</>}
  </div></div>
}
